import type { ClinicalInitSeedRecord } from "../record";

export const records: ClinicalInitSeedRecord[] = [
	{
		recordId: "variation.date.primary",
		kind: "variation_group",
		profileId: "starter.default",
		requires: ["starter.date-pattern"],
		variationGroup: "date.primary",
		variationId: "variation.date.primary",
		variationPriority: 100,
		ambiguityPolicy: "highest_priority",
		payload: {
			semanticTarget: "date",
			tokens: ["YYYY", "MM", "DD"],
			separators: ["-", "-"],
			description: "ISO 8601 date pattern (YYYY-MM-DD)",
		},
	},
	{
		recordId: "variation.date.european",
		kind: "variation_group",
		profileId: "starter.default",
		requires: ["starter.date-pattern"],
		variationGroup: "date.primary",
		variationId: "variation.date.european",
		variationPriority: 90,
		ambiguityPolicy: "highest_priority",
		payload: {
			semanticTarget: "date",
			tokens: ["DD", "MM", "YYYY"],
			separators: ["/", "/"],
			description: "European date pattern (DD/MM/YYYY)",
		},
	},
	{
		recordId: "variation.date.named-month",
		kind: "variation_group",
		profileId: "starter.default",
		requires: ["starter.date-pattern", "starter.calendar-vocabulary"],
		variationGroup: "date.primary",
		variationId: "variation.date.named-month",
		variationPriority: 80,
		ambiguityPolicy: "highest_priority",
		payload: {
			semanticTarget: "date",
			tokens: ["DD", "MM_name", "YYYY"],
			separators: [" ", " "],
			description: "Named month date pattern (DD Month YYYY)",
		},
	},
	{
		recordId: "variation.tag.observation",
		kind: "variation_group",
		profileId: "starter.default",
		requires: ["starter.profile"],
		variationGroup: "tag.observation",
		variationId: "variation.tag.observation",
		variationPriority: 100,
		ambiguityPolicy: "first",
		payload: {
			semanticTarget: "observation",
			aliases: ["#obs", "#observation"],
			description: "Observation tag aliases",
		},
	},
	{
		recordId: "variation.tag.measurement",
		kind: "variation_group",
		profileId: "starter.default",
		requires: ["starter.profile"],
		variationGroup: "tag.measurement",
		variationId: "variation.tag.measurement",
		variationPriority: 100,
		ambiguityPolicy: "first",
		payload: {
			semanticTarget: "measurement",
			aliases: ["#meas", "#measurement"],
			description: "Measurement tag aliases",
		},
	},
	{
		recordId: "variation.relative-time.past-first",
		kind: "variation_group",
		profileId: "starter.default",
		requires: ["starter.relative-time"],
		variationGroup: "relative_time.past",
		variationId: "variation.relative-time.past-first",
		variationPriority: 100,
		ambiguityPolicy: "highest_priority",
		payload: {
			semanticTarget: "ClinicalDateRange.relativeEstimate",
			sequence: ["magnitude", "precisionUnit", "directionAnchor"],
			direction: "retrospective",
			description: "Magnitude then unit then direction (e.g. '3 wks ago')",
		},
	},
	{
		recordId: "variation.relative-time.past-second",
		kind: "variation_group",
		profileId: "starter.default",
		requires: ["starter.relative-time"],
		variationGroup: "relative_time.past",
		variationId: "variation.relative-time.past-second",
		variationPriority: 90,
		ambiguityPolicy: "highest_priority",
		payload: {
			semanticTarget: "ClinicalDateRange.relativeEstimate",
			sequence: ["directionAnchor", "magnitude", "precisionUnit"],
			direction: "retrospective",
			description: "Direction then magnitude then unit (e.g. 'hace 3 sem')",
		},
	},
];