import { defineSchema } from "../schema-factory";

export const soapNoteSchema = defineSchema({
	schema: "Note",
	version: 1,
	status: "published",
	fields: {
		id: {
			path: "id",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: true,
		},
		title: {
			path: "title",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: true,
		},
		createdAt: {
			path: "createdAt",
			valueKind: "temporal",
			temporalType: "date",
			cardinality: "one",
			required: true,
		},
		updatedAt: {
			path: "updatedAt",
			valueKind: "temporal",
			temporalType: "date",
			cardinality: "one",
			required: true,
		},
		status: {
			path: "status",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: ["draft", "signed", "amended", "voided"],
		},
		signedBy: {
			path: "signedBy",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: false,
		},
		patient: {
			path: "patient",
			valueKind: "composite",
			cardinality: "one",
			required: true,
		},
		subjective: {
			path: "subjective",
			valueKind: "composite",
			cardinality: "one",
			required: true,
		},
		"subjective.presentingComplaint": {
			path: "subjective.presentingComplaint",
			valueKind: "composite",
			cardinality: "one",
			required: true,
		},
		"subjective.patientHistories": {
			path: "subjective.patientHistories",
			valueKind: "composite",
			cardinality: "one",
			required: true,
		},
		objective: {
			path: "objective",
			valueKind: "composite",
			cardinality: "one",
			required: true,
		},
		"objective.vitalSigns": {
			path: "objective.vitalSigns",
			valueKind: "composite",
			cardinality: "many",
			required: true,
		},
		"objective.physicalExamination": {
			path: "objective.physicalExamination",
			valueKind: "composite",
			cardinality: "many",
			required: false,
		},
		"objective.labResults": {
			path: "objective.labResults",
			valueKind: "composite",
			cardinality: "many",
			required: false,
		},
		"objective.narrative": {
			path: "objective.narrative",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: false,
		},
		assessment: {
			path: "assessment",
			valueKind: "composite",
			cardinality: "one",
			required: true,
		},
		"assessment.primaryDiagnosis": {
			path: "assessment.primaryDiagnosis",
			valueKind: "composite",
			cardinality: "one",
			required: false,
		},
		"assessment.differentialDiagnoses": {
			path: "assessment.differentialDiagnoses",
			valueKind: "composite",
			cardinality: "many",
			required: true,
		},
		"assessment.narrative": {
			path: "assessment.narrative",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: false,
		},
		plan: {
			path: "plan",
			valueKind: "composite",
			cardinality: "one",
			required: true,
		},
		"plan.prescriptions": {
			path: "plan.prescriptions",
			valueKind: "composite",
			cardinality: "many",
			required: false,
		},
		"plan.investigations": {
			path: "plan.investigations",
			valueKind: "composite",
			cardinality: "many",
			required: false,
		},
		"plan.referrals": {
			path: "plan.referrals",
			valueKind: "composite",
			cardinality: "many",
			required: false,
		},
		"plan.interventions": {
			path: "plan.interventions",
			valueKind: "composite",
			cardinality: "many",
			required: false,
		},
		"plan.narrative": {
			path: "plan.narrative",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: false,
		},
	},
});
