import {
	AQUATIC_TERRAINS,
	ATMOSPHERIC_TERRAINS,
	BUILDING_TYPES,
	CELESTIAL_SPACE_TERRAINS,
	COMBAT_ENGAGEMENT_LEVELS,
	CONTEXT_TYPES,
	CONTROL_MODALITIES,
	COORDINATE_DATUMS,
	EMPLOYMENT_REGIMES,
	ERGONOMIC_MODALITIES,
	OPERATIONAL_DOMAINS,
	TERRESTRIAL_TERRAINS,
	TRANSPORT_MODES,
	VEHICLE_CHASSIS_CATEGORIES,
	VEHICLE_USAGES,
	WEATHER_CONDITIONS,
} from "../../../schemas/environment";
import { CLINICAL_SOURCE_TYPES } from "../../../schemas/shared";
import { defineSchema } from "../schema-factory";
import { productDetailsFields } from "./shared-fields";

const COMBINED_TERRAINS = [
	...TERRESTRIAL_TERRAINS,
	...AQUATIC_TERRAINS,
	...ATMOSPHERIC_TERRAINS,
	...CELESTIAL_SPACE_TERRAINS,
] as const;

export const environmentSchema = defineSchema({
	schema: "Environment",
	version: 1,
	status: "published",
	fields: {
		id: {
			path: "id",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: true,
		},
		soapSection: {
			path: "soapSection",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: ["subjective", "objective"],
		},
		contextType: {
			path: "contextType",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: CONTEXT_TYPES,
		},
		sourceType: {
			path: "sourceType",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: CLINICAL_SOURCE_TYPES,
		},
		dateRange: {
			path: "dateRange",
			valueKind: "temporal",
			temporalType: "date_range",
			cardinality: "one",
			required: false,
		},
		countryCode: {
			path: "countryCode",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: false,
		},
		subdivisionStateCode: {
			path: "subdivisionStateCode",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: false,
		},
		postalRoutingCode: {
			path: "postalRoutingCode",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: false,
		},
		facilityId: {
			path: "facilityId",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: false,
		},
		referenceFrame: {
			path: "referenceFrame",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: COORDINATE_DATUMS,
		},
		coordinateAlpha: {
			path: "coordinateAlpha",
			valueKind: "scalar",
			scalarType: "number",
			cardinality: "one",
			required: false,
		},
		coordinateBeta: {
			path: "coordinateBeta",
			valueKind: "scalar",
			scalarType: "number",
			cardinality: "one",
			required: false,
		},
		coordinateGamma: {
			path: "coordinateGamma",
			valueKind: "scalar",
			scalarType: "number",
			cardinality: "one",
			required: false,
		},
		uncertaintyRadius: {
			path: "uncertaintyRadius",
			valueKind: "measurement",
			measurement: { dimension: "length" },
			cardinality: "one",
			required: false,
		},
		temperature: {
			path: "temperature",
			valueKind: "measurement",
			measurement: { dimension: "temperature" },
			cardinality: "one",
			required: false,
		},
		relativeHumidityPct: {
			path: "relativeHumidityPct",
			valueKind: "scalar",
			scalarType: "number",
			cardinality: "one",
			required: false,
		},
		barometricPressure: {
			path: "barometricPressure",
			valueKind: "measurement",
			measurement: { dimension: "pressure" },
			cardinality: "one",
			required: false,
		},
		airQualityIndexAqi: {
			path: "airQualityIndexAqi",
			valueKind: "scalar",
			scalarType: "number",
			cardinality: "one",
			required: false,
		},
		particulateMatter25: {
			path: "particulateMatter25",
			valueKind: "scalar",
			scalarType: "number",
			cardinality: "one",
			required: false,
		},
		weatherType: {
			path: "weatherType",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: WEATHER_CONDITIONS,
		},
		engagementLevel: {
			path: "engagementLevel",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: COMBAT_ENGAGEMENT_LEVELS,
		},
		threatZone: {
			path: "threatZone",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: false,
		},
		description: {
			path: "description",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: false,
		},
		employmentRegime: {
			path: "employmentRegime",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: EMPLOYMENT_REGIMES,
		},
		ergonomicModality: {
			path: "ergonomicModality",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: ERGONOMIC_MODALITIES,
		},
		continuousShiftHours: {
			path: "continuousShiftHours",
			valueKind: "scalar",
			scalarType: "number",
			cardinality: "one",
			required: false,
		},
		metabolicRateMets: {
			path: "metabolicRateMets",
			valueKind: "scalar",
			scalarType: "number",
			cardinality: "one",
			required: false,
		},
		operationalDomain: {
			path: "operationalDomain",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: OPERATIONAL_DOMAINS,
		},
		terrain: {
			path: "terrain",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: COMBINED_TERRAINS,
		},
		buildingType: {
			path: "buildingType",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: BUILDING_TYPES,
		},
		elevation: {
			path: "elevation",
			valueKind: "measurement",
			measurement: { dimension: "length" },
			cardinality: "one",
			required: false,
		},
		submersionDepth: {
			path: "submersionDepth",
			valueKind: "measurement",
			measurement: { dimension: "length" },
			cardinality: "one",
			required: false,
		},
		orbitalAltitude: {
			path: "orbitalAltitude",
			valueKind: "measurement",
			measurement: { dimension: "length" },
			cardinality: "one",
			required: false,
		},
		vehicleCategory: {
			path: "vehicleCategory",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: VEHICLE_CHASSIS_CATEGORIES,
		},
		transportMode: {
			path: "transportMode",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: TRANSPORT_MODES,
		},
		controlModality: {
			path: "controlModality",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: CONTROL_MODALITIES,
		},
		usage: {
			path: "usage",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: VEHICLE_USAGES,
		},
		isArmored: {
			path: "isArmored",
			valueKind: "scalar",
			scalarType: "boolean",
			cardinality: "one",
			required: false,
		},
		...productDetailsFields({ name: "details" }),
	},
});
