import {
	BIOLOGICAL_MECHANISMS,
	CHEMICAL_FORMS,
	COMPLIANCE_STATUSES,
	EXPOSURE_TYPES,
	PATHOGEN_VECTOR_STATUSES,
} from "../../../schemas/exposure";
import { ROUTES } from "../../../schemas/shared";
import { defineSchema } from "../schema-factory";
import { anatomyLocationsFields, frequencyFields } from "./shared-fields";

export const exposureSchema = defineSchema({
	schema: "Exposure",
	version: 1,
	status: "published",
	fields: {
		id: {
			path: "id",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: true,
		},
		exposureType: {
			path: "exposureType",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: EXPOSURE_TYPES,
		},
		substance: {
			path: "substance",
			valueKind: "concept",
			cardinality: "one",
			required: false,
			conceptResolution: { required: true },
		},
		route: {
			path: "route",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: ROUTES,
		},
		dateRange: {
			path: "dateRange",
			valueKind: "temporal",
			temporalType: "date_range",
			cardinality: "one",
			required: false,
		},
		...frequencyFields(),
		form: {
			path: "form",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: CHEMICAL_FORMS,
		},
		complianceStatus: {
			path: "complianceStatus",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: COMPLIANCE_STATUSES,
		},
		dosage: {
			path: "dosage",
			valueKind: "measurement",
			cardinality: "one",
			required: false,
			measurement: { dimension: "mass_concentration" },
		},
		count: {
			path: "count",
			valueKind: "measurement",
			cardinality: "many",
			required: false,
			measurement: { dimension: "count" },
		},
		species: {
			path: "species",
			valueKind: "concept",
			cardinality: "one",
			required: false,
			conceptResolution: { required: true },
		},
		breedOrCultivar: {
			path: "breedOrCultivar",
			valueKind: "concept",
			cardinality: "one",
			required: false,
			conceptResolution: { required: true },
		},
		mechanism: {
			path: "mechanism",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: BIOLOGICAL_MECHANISMS,
		},
		isToxicOrVenomous: {
			path: "isToxicOrVenomous",
			valueKind: "scalar",
			scalarType: "boolean",
			cardinality: "one",
			required: false,
		},
		pathogenVectorStatus: {
			path: "pathogenVectorStatus",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: PATHOGEN_VECTOR_STATUSES,
		},
		...anatomyLocationsFields(),
		carriedPathogen: {
			path: "carriedPathogen",
			valueKind: "concept",
			cardinality: "one",
			required: false,
			conceptResolution: { required: true },
		},
		side_effects: {
			path: "side_effects",
			valueKind: "composite",
			cardinality: "one",
			required: false,
		},
		"side_effects.allergic": {
			path: "side_effects.allergic",
			valueKind: "scalar",
			scalarType: "boolean",
			cardinality: "one",
			required: false,
		},
		"side_effects.intolerant": {
			path: "side_effects.intolerant",
			valueKind: "scalar",
			scalarType: "boolean",
			cardinality: "one",
			required: false,
		},
		"side_effects.adverse_reaction": {
			path: "side_effects.adverse_reaction",
			valueKind: "scalar",
			scalarType: "boolean",
			cardinality: "one",
			required: false,
		},
	},
});
