import {
	ALLERGY_SEVERITIES,
	ALLERGY_VERIFICATION_STATUSES,
	COMPLIANCE_STATUSES,
	SOCIAL_HISTORY_STATUSES,
} from "../schemas-interface/history";
import { CLINICAL_SOURCE_TYPES } from "../schemas-interface/shared";
import { defineSchema } from "../schema-factory";
import { frequencyFields } from "./shared-fields";

export const historySchema = defineSchema({
	schema: "History",
	version: 1,
	status: "published",
	fields: {
		pastMedicalHistory: {
			path: "pastMedicalHistory",
			valueKind: "concept_array",
			cardinality: "many",
			required: true,
			conceptResolution: { required: true },
		},
		currentMedications: {
			path: "currentMedications",
			valueKind: "composite",
			cardinality: "many",
			required: true,
		},
		"currentMedications[].medication": {
			path: "currentMedications[].medication",
			valueKind: "concept",
			cardinality: "one",
			required: true,
			conceptResolution: { required: true },
		},
		"currentMedications[].complianceStatus": {
			path: "currentMedications[].complianceStatus",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: COMPLIANCE_STATUSES,
		},
		"currentMedications[].sourceType": {
			path: "currentMedications[].sourceType",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: CLINICAL_SOURCE_TYPES,
		},
		"currentMedications[].dosage": {
			path: "currentMedications[].dosage",
			valueKind: "measurement",
			cardinality: "one",
			required: false,
			measurement: { dimension: "mass_concentration" },
		},
		"currentMedications[].count": {
			path: "currentMedications[].count",
			valueKind: "measurement",
			cardinality: "many",
			required: false,
			measurement: { dimension: "count" },
		},
		...frequencyFields({ base: "currentMedications[]" }),
		"currentMedications[].dateRange": {
			path: "currentMedications[].dateRange",
			valueKind: "temporal",
			temporalType: "date_range",
			cardinality: "one",
			required: false,
		},
		allergies: {
			path: "allergies",
			valueKind: "composite",
			cardinality: "many",
			required: true,
		},
		"allergies[].substance": {
			path: "allergies[].substance",
			valueKind: "concept",
			cardinality: "one",
			required: true,
			conceptResolution: { required: true },
		},
		"allergies[].verificationStatus": {
			path: "allergies[].verificationStatus",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: ALLERGY_VERIFICATION_STATUSES,
		},
		"allergies[].reactionType": {
			path: "allergies[].reactionType",
			valueKind: "concept_array",
			cardinality: "many",
			required: false,
			conceptResolution: { required: true },
		},
		"allergies[].allergySeverity": {
			path: "allergies[].allergySeverity",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: ALLERGY_SEVERITIES,
		},
		"allergies[].onsetDateRange": {
			path: "allergies[].onsetDateRange",
			valueKind: "temporal",
			temporalType: "date_range",
			cardinality: "one",
			required: false,
		},
		familyHistory: {
			path: "familyHistory",
			valueKind: "concept_array",
			cardinality: "many",
			required: false,
			conceptResolution: { required: true },
		},
		socialHistory: {
			path: "socialHistory",
			valueKind: "composite",
			cardinality: "many",
			required: false,
		},
		"socialHistory[].status": {
			path: "socialHistory[].status",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: SOCIAL_HISTORY_STATUSES,
		},
		"socialHistory[].category": {
			path: "socialHistory[].category",
			valueKind: "concept",
			cardinality: "one",
			required: true,
			conceptResolution: { required: true },
		},
		"socialHistory[].count": {
			path: "socialHistory[].count",
			valueKind: "measurement",
			cardinality: "many",
			required: false,
			measurement: { dimension: "count" },
		},
		...frequencyFields({ base: "socialHistory[]" }),
		"socialHistory[].dateRange": {
			path: "socialHistory[].dateRange",
			valueKind: "temporal",
			temporalType: "date_range",
			cardinality: "one",
			required: false,
		},
		"socialHistory[].notes": {
			path: "socialHistory[].notes",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: false,
		},
		immunizations: {
			path: "immunizations",
			valueKind: "concept_array",
			cardinality: "many",
			required: false,
			conceptResolution: { required: true },
		},
		surgicalHistory: {
			path: "surgicalHistory",
			valueKind: "concept_array",
			cardinality: "many",
			required: false,
			conceptResolution: { required: true },
		},
	},
});
