import {
	ANESTHESIA_TYPES,
	ESCALATION_PATHS,
	INVESTIGATION_TYPES,
	PRIORITIES,
	REFERRAL_URGENCIES,
} from "../../../schemas/plan";
import { LATERALITIES } from "../../../schemas/shared";
import { defineSchema } from "../schema-factory";

export const investigationOrderSchema = defineSchema({
	schema: "InvestigationOrder",
	version: 1,
	status: "published",
	fields: {
		id: {
			path: "id",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: true,
		},
		procedure: {
			path: "procedure",
			valueKind: "concept",
			cardinality: "one",
			required: true,
			conceptResolution: { required: true },
		},
		rawTerm: {
			path: "rawTerm",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: false,
		},
		priority: {
			path: "priority",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: PRIORITIES,
		},
		reason: {
			path: "reason",
			valueKind: "concept",
			cardinality: "one",
			required: false,
			conceptResolution: { required: true },
		},
		dateRange: {
			path: "dateRange",
			valueKind: "temporal",
			temporalType: "date_range",
			cardinality: "one",
			required: false,
		},
		investigationType: {
			path: "investigationType",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: INVESTIGATION_TYPES,
		},
		specimenType: {
			path: "specimenType",
			valueKind: "concept",
			cardinality: "one",
			required: false,
			conceptResolution: { required: true },
		},
		panelCode: {
			path: "panelCode",
			valueKind: "concept",
			cardinality: "one",
			required: false,
			conceptResolution: { required: true },
		},
		laterality: {
			path: "laterality",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: LATERALITIES,
		},
	},
});

export const referralOrderSchema = defineSchema({
	schema: "ReferralOrder",
	version: 1,
	status: "published",
	fields: {
		id: {
			path: "id",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: true,
		},
		procedure: {
			path: "procedure",
			valueKind: "concept",
			cardinality: "one",
			required: true,
			conceptResolution: { required: true },
		},
		rawTerm: {
			path: "rawTerm",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: false,
		},
		priority: {
			path: "priority",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: PRIORITIES,
		},
		reason: {
			path: "reason",
			valueKind: "concept",
			cardinality: "one",
			required: false,
			conceptResolution: { required: true },
		},
		dateRange: {
			path: "dateRange",
			valueKind: "temporal",
			temporalType: "date_range",
			cardinality: "one",
			required: false,
		},
		specialistDiscipline: {
			path: "specialistDiscipline",
			valueKind: "concept",
			cardinality: "one",
			required: true,
			conceptResolution: { required: true },
		},
		referralUrgency: {
			path: "referralUrgency",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: REFERRAL_URGENCIES,
		},
		clinicalQuestion: {
			path: "clinicalQuestion",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: false,
		},
		routingNotes: {
			path: "routingNotes",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: false,
		},
	},
});

export const interventionOrderSchema = defineSchema({
	schema: "InterventionOrder",
	version: 1,
	status: "published",
	fields: {
		id: {
			path: "id",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: true,
		},
		procedure: {
			path: "procedure",
			valueKind: "concept",
			cardinality: "one",
			required: true,
			conceptResolution: { required: true },
		},
		rawTerm: {
			path: "rawTerm",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: false,
		},
		priority: {
			path: "priority",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: PRIORITIES,
		},
		reason: {
			path: "reason",
			valueKind: "concept",
			cardinality: "one",
			required: false,
			conceptResolution: { required: true },
		},
		dateRange: {
			path: "dateRange",
			valueKind: "temporal",
			temporalType: "date_range",
			cardinality: "one",
			required: false,
		},
		procedureLocation: {
			path: "procedureLocation",
			valueKind: "concept",
			cardinality: "one",
			required: false,
			conceptResolution: { required: true },
		},
		anesthesiaType: {
			path: "anesthesiaType",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: ANESTHESIA_TYPES,
		},
		schedulingWindow: {
			path: "schedulingWindow",
			valueKind: "temporal",
			temporalType: "date_range",
			cardinality: "one",
			required: false,
		},
	},
});

export const safetyNettingSchema = defineSchema({
	schema: "SafetyNetting",
	version: 1,
	status: "published",
	fields: {
		redFlagSymptoms: {
			path: "redFlagSymptoms",
			valueKind: "concept_array",
			cardinality: "many",
			required: true,
			conceptResolution: { required: true },
		},
		returnPrecautions: {
			path: "returnPrecautions",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: true,
		},
		followUpWindow: {
			path: "followUpWindow",
			valueKind: "temporal",
			temporalType: "date_range",
			cardinality: "one",
			required: true,
		},
		followUpTriggers: {
			path: "followUpTriggers",
			valueKind: "concept_array",
			cardinality: "many",
			required: false,
			conceptResolution: { required: true },
		},
		escalationPath: {
			path: "escalationPath",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: ESCALATION_PATHS,
		},
	},
});

export const militaryPlanExtensionSchema = defineSchema({
	schema: "MilitaryPlanExtension",
	version: 1,
	status: "published",
	fields: {
		disposition: {
			path: "disposition",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: [
				"return_to_duty",
				"sick_in_quarters",
				"light_duty",
				"limited_duty",
				"medevac_requested",
				"admitted_to_mtf",
			],
		},
		dutyLimitations: {
			path: "dutyLimitations",
			valueKind: "composite",
			cardinality: "one",
			required: false,
		},
		"dutyLimitations.running": {
			path: "dutyLimitations.running",
			valueKind: "scalar",
			scalarType: "boolean",
			cardinality: "one",
			required: false,
		},
		"dutyLimitations.cycling": {
			path: "dutyLimitations.cycling",
			valueKind: "scalar",
			scalarType: "boolean",
			cardinality: "one",
			required: false,
		},
		"dutyLimitations.swimming": {
			path: "dutyLimitations.swimming",
			valueKind: "scalar",
			scalarType: "boolean",
			cardinality: "one",
			required: false,
		},
		"dutyLimitations.max_lifting_lbs": {
			path: "dutyLimitations.max_lifting_lbs",
			valueKind: "scalar",
			scalarType: "number",
			cardinality: "one",
			required: false,
		},
		"dutyLimitations.body_armor_or_helmet": {
			path: "dutyLimitations.body_armor_or_helmet",
			valueKind: "scalar",
			scalarType: "boolean",
			cardinality: "one",
			required: false,
		},
		"dutyLimitations.weapon_handling": {
			path: "dutyLimitations.weapon_handling",
			valueKind: "scalar",
			scalarType: "boolean",
			cardinality: "one",
			required: false,
		},
		"dutyLimitations.profile_duration_days": {
			path: "dutyLimitations.profile_duration_days",
			valueKind: "scalar",
			scalarType: "number",
			cardinality: "one",
			required: false,
		},
	},
});
