import {
	affine,
	ENERGY_VECTOR,
	FORCE_VECTOR,
	FREQUENCY_VECTOR,
	LENGTH_VECTOR,
	MASS_VECTOR,
	POWER_VECTOR,
	PRESSURE_VECTOR,
	type StandardUnit,
	standard,
	TEMPERATURE_VECTOR,
	TIME_VECTOR,
	VOLUME_VECTOR,
} from "./factory";
import type { CommonUnitCatalogOptions } from "./types";

export function timeUnits(options: CommonUnitCatalogOptions): StandardUnit[] {
	const weekSeconds = options.timeDefaults?.weekSeconds ?? 7 * 86_400;
	const monthSeconds = options.timeDefaults?.monthSeconds ?? 30.436875 * 86_400;
	const yearSeconds = options.timeDefaults?.yearSeconds ?? 365.2425 * 86_400;
	for (const [name, value] of Object.entries({
		weekSeconds,
		monthSeconds,
		yearSeconds,
	})) {
		if (!Number.isFinite(value) || value <= 0)
			throw new Error(`${name} must be a finite positive number`);
	}
	return [
		standard({
			id: "s",
			dimension: "time",
			canonicalUnit: "d",
			baseUnit: "s",
			baseDimensionVector: TIME_VECTOR,
			composable: true,
			bundle: "si",
			factor: 1,
		}),
		standard({
			id: "min",
			dimension: "time",
			canonicalUnit: "d",
			baseUnit: "s",
			baseDimensionVector: TIME_VECTOR,
			composable: true,
			bundle: "si",
			factor: 60,
		}),
		standard({
			id: "h",
			dimension: "time",
			canonicalUnit: "d",
			baseUnit: "s",
			baseDimensionVector: TIME_VECTOR,
			composable: true,
			bundle: "si",
			factor: 3_600,
		}),
		standard({
			id: "d",
			dimension: "time",
			canonicalUnit: "d",
			baseUnit: "s",
			baseDimensionVector: TIME_VECTOR,
			composable: true,
			bundle: "si",
			factor: 86_400,
		}),
		standard({
			id: "wk",
			dimension: "time",
			canonicalUnit: "d",
			baseUnit: "s",
			baseDimensionVector: TIME_VECTOR,
			composable: true,
			bundle: "si",
			factor: weekSeconds,
		}),
		standard({
			id: "mo",
			dimension: "time",
			canonicalUnit: "d",
			baseUnit: "s",
			baseDimensionVector: TIME_VECTOR,
			composable: true,
			bundle: "si",
			factor: monthSeconds,
		}),
		standard({
			id: "a",
			dimension: "time",
			canonicalUnit: "d",
			baseUnit: "s",
			baseDimensionVector: TIME_VECTOR,
			composable: true,
			bundle: "si",
			factor: yearSeconds,
		}),
	];
}

export function siUnits(options: CommonUnitCatalogOptions): StandardUnit[] {
	return [
		standard({
			id: "m",
			dimension: "length",
			canonicalUnit: "m",
			baseDimensionVector: LENGTH_VECTOR,
			composable: true,
			bundle: "si",
			factor: 1,
		}),
		standard({
			id: "km",
			dimension: "length",
			canonicalUnit: "m",
			baseDimensionVector: LENGTH_VECTOR,
			composable: true,
			bundle: "si",
			factor: 1_000,
		}),
		standard({
			id: "cm",
			dimension: "length",
			canonicalUnit: "m",
			baseDimensionVector: LENGTH_VECTOR,
			composable: true,
			bundle: "si",
			factor: 0.01,
		}),
		standard({
			id: "mm",
			dimension: "length",
			canonicalUnit: "m",
			baseDimensionVector: LENGTH_VECTOR,
			composable: true,
			bundle: "si",
			factor: 0.001,
		}),
		standard({
			id: "um",
			dimension: "length",
			canonicalUnit: "m",
			baseDimensionVector: LENGTH_VECTOR,
			composable: true,
			bundle: "si",
			factor: 1e-6,
		}),
		standard({
			id: "nm",
			dimension: "length",
			canonicalUnit: "m",
			baseDimensionVector: LENGTH_VECTOR,
			composable: true,
			bundle: "si",
			factor: 1e-9,
		}),
		standard({
			id: "kg",
			dimension: "mass",
			canonicalUnit: "kg",
			baseDimensionVector: MASS_VECTOR,
			composable: true,
			bundle: "si",
			factor: 1,
		}),
		standard({
			id: "g",
			dimension: "mass",
			canonicalUnit: "kg",
			baseDimensionVector: MASS_VECTOR,
			composable: true,
			bundle: "si",
			factor: 0.001,
		}),
		standard({
			id: "mg",
			dimension: "mass",
			canonicalUnit: "kg",
			baseDimensionVector: MASS_VECTOR,
			composable: true,
			bundle: "si",
			factor: 1e-6,
		}),
		standard({
			id: "ug",
			dimension: "mass",
			canonicalUnit: "kg",
			baseDimensionVector: MASS_VECTOR,
			composable: true,
			bundle: "si",
			factor: 1e-9,
		}),
		standard({
			id: "ng",
			dimension: "mass",
			canonicalUnit: "kg",
			baseDimensionVector: MASS_VECTOR,
			composable: true,
			bundle: "si",
			factor: 1e-12,
		}),
		standard({
			id: "m3",
			dimension: "volume",
			canonicalUnit: "L",
			baseUnit: "m3",
			baseDimensionVector: VOLUME_VECTOR,
			composable: true,
			bundle: "si",
			factor: 1,
		}),
		standard({
			id: "L",
			dimension: "volume",
			canonicalUnit: "L",
			baseUnit: "m3",
			baseDimensionVector: VOLUME_VECTOR,
			composable: true,
			bundle: "si",
			factor: 0.001,
		}),
		standard({
			id: "dL",
			dimension: "volume",
			canonicalUnit: "L",
			baseUnit: "m3",
			baseDimensionVector: VOLUME_VECTOR,
			composable: true,
			bundle: "si",
			factor: 0.0001,
		}),
		standard({
			id: "mL",
			dimension: "volume",
			canonicalUnit: "L",
			baseUnit: "m3",
			baseDimensionVector: VOLUME_VECTOR,
			composable: true,
			bundle: "si",
			factor: 1e-6,
		}),
		standard({
			id: "uL",
			dimension: "volume",
			canonicalUnit: "L",
			baseUnit: "m3",
			baseDimensionVector: VOLUME_VECTOR,
			composable: true,
			bundle: "si",
			factor: 1e-9,
		}),
		affine({
			id: "K",
			dimension: "temperature",
			canonicalUnit: "K",
			baseDimensionVector: TEMPERATURE_VECTOR,
			composable: false,
			bundle: "si",
			toBase: (value) => value,
			fromBase: (value) => value,
		}),
		affine({
			id: "Cel",
			dimension: "temperature",
			canonicalUnit: "K",
			baseDimensionVector: TEMPERATURE_VECTOR,
			composable: false,
			bundle: "si",
			toBase: (value) => value + 273.15,
			fromBase: (value) => value - 273.15,
		}),
		standard({
			id: "Pa",
			dimension: "pressure",
			canonicalUnit: "Pa",
			baseDimensionVector: PRESSURE_VECTOR,
			composable: true,
			bundle: "si",
			factor: 1,
		}),
		standard({
			id: "kPa",
			dimension: "pressure",
			canonicalUnit: "Pa",
			baseDimensionVector: PRESSURE_VECTOR,
			composable: true,
			bundle: "si",
			factor: 1_000,
		}),
		standard({
			id: "bar",
			dimension: "pressure",
			canonicalUnit: "Pa",
			baseDimensionVector: PRESSURE_VECTOR,
			composable: true,
			bundle: "si",
			factor: 100_000,
		}),
		standard({
			id: "mm[Hg]",
			dimension: "pressure",
			canonicalUnit: "Pa",
			baseDimensionVector: PRESSURE_VECTOR,
			composable: true,
			bundle: "si",
			factor: 133.322387415,
		}),
		standard({
			id: "N",
			dimension: "force",
			canonicalUnit: "N",
			baseDimensionVector: FORCE_VECTOR,
			composable: true,
			bundle: "si",
			factor: 1,
		}),
		standard({
			id: "J",
			dimension: "energy",
			canonicalUnit: "J",
			baseDimensionVector: ENERGY_VECTOR,
			composable: true,
			bundle: "si",
			factor: 1,
		}),
		standard({
			id: "[cal_IT]",
			dimension: "energy",
			canonicalUnit: "J",
			baseDimensionVector: ENERGY_VECTOR,
			composable: true,
			bundle: "si",
			factor: 4.1868,
		}),
		standard({
			id: "W",
			dimension: "power",
			canonicalUnit: "W",
			baseDimensionVector: POWER_VECTOR,
			composable: true,
			bundle: "si",
			factor: 1,
		}),
		standard({
			id: "Hz",
			dimension: "frequency",
			canonicalUnit: "Hz",
			baseDimensionVector: FREQUENCY_VECTOR,
			composable: true,
			bundle: "si",
			factor: 1,
		}),
		...timeUnits(options),
	];
}
