import {
	affine,
	ENERGY_VECTOR,
	FORCE_VECTOR,
	LENGTH_VECTOR,
	MASS_VECTOR,
	POWER_VECTOR,
	PRESSURE_VECTOR,
	type StandardUnit,
	standard,
	TEMPERATURE_VECTOR,
	VOLUME_VECTOR,
} from "./factory";

export function usCustomaryUnits(): StandardUnit[] {
	return [
		standard({
			id: "[in_i]",
			dimension: "length",
			canonicalUnit: "m",
			baseDimensionVector: LENGTH_VECTOR,
			composable: true,
			bundle: "us-customary",
			factor: 0.0254,
		}),
		standard({
			id: "[ft_i]",
			dimension: "length",
			canonicalUnit: "m",
			baseDimensionVector: LENGTH_VECTOR,
			composable: true,
			bundle: "us-customary",
			factor: 0.3048,
		}),
		standard({
			id: "[yd_i]",
			dimension: "length",
			canonicalUnit: "m",
			baseDimensionVector: LENGTH_VECTOR,
			composable: true,
			bundle: "us-customary",
			factor: 0.9144,
		}),
		standard({
			id: "[mi_i]",
			dimension: "length",
			canonicalUnit: "m",
			baseDimensionVector: LENGTH_VECTOR,
			composable: true,
			bundle: "us-customary",
			factor: 1_609.344,
		}),
		standard({
			id: "[lb_av]",
			dimension: "mass",
			canonicalUnit: "kg",
			baseDimensionVector: MASS_VECTOR,
			composable: true,
			bundle: "us-customary",
			factor: 0.45359237,
		}),
		standard({
			id: "[oz_av]",
			dimension: "mass",
			canonicalUnit: "kg",
			baseDimensionVector: MASS_VECTOR,
			composable: true,
			bundle: "us-customary",
			factor: 0.028349523125,
		}),
		standard({
			id: "[gal_us]",
			dimension: "volume",
			canonicalUnit: "L",
			baseUnit: "m3",
			baseDimensionVector: VOLUME_VECTOR,
			composable: true,
			bundle: "us-customary",
			factor: 0.003785411784,
		}),
		standard({
			id: "[qt_us]",
			dimension: "volume",
			canonicalUnit: "L",
			baseUnit: "m3",
			baseDimensionVector: VOLUME_VECTOR,
			composable: true,
			bundle: "us-customary",
			factor: 0.000946352946,
		}),
		standard({
			id: "[pt_us]",
			dimension: "volume",
			canonicalUnit: "L",
			baseUnit: "m3",
			baseDimensionVector: VOLUME_VECTOR,
			composable: true,
			bundle: "us-customary",
			factor: 0.000473176473,
		}),
		standard({
			id: "[foz_us]",
			dimension: "volume",
			canonicalUnit: "L",
			baseUnit: "m3",
			baseDimensionVector: VOLUME_VECTOR,
			composable: true,
			bundle: "us-customary",
			factor: 0.0000295735295625,
		}),
		standard({
			id: "[cup_us]",
			dimension: "volume",
			canonicalUnit: "L",
			baseUnit: "m3",
			baseDimensionVector: VOLUME_VECTOR,
			composable: true,
			bundle: "us-customary",
			factor: 0.0002365882365,
		}),
		standard({
			id: "[tbsp_us]",
			dimension: "volume",
			canonicalUnit: "L",
			baseUnit: "m3",
			baseDimensionVector: VOLUME_VECTOR,
			composable: true,
			bundle: "us-customary",
			factor: 0.00001478676478125,
		}),
		standard({
			id: "[tsp_us]",
			dimension: "volume",
			canonicalUnit: "L",
			baseUnit: "m3",
			baseDimensionVector: VOLUME_VECTOR,
			composable: true,
			bundle: "us-customary",
			factor: 0.00000492892159375,
		}),
		affine({
			id: "[degF]",
			dimension: "temperature",
			canonicalUnit: "K",
			baseDimensionVector: TEMPERATURE_VECTOR,
			composable: false,
			bundle: "us-customary",
			toBase: (value) => (value - 32) * (5 / 9) + 273.15,
			fromBase: (value) => (value - 273.15) * (9 / 5) + 32,
		}),
		standard({
			id: "[psi]",
			dimension: "pressure",
			canonicalUnit: "Pa",
			baseDimensionVector: PRESSURE_VECTOR,
			composable: true,
			bundle: "us-customary",
			factor: 6_894.757293168,
		}),
		standard({
			id: "[lbf_av]",
			dimension: "force",
			canonicalUnit: "N",
			baseDimensionVector: FORCE_VECTOR,
			composable: true,
			bundle: "us-customary",
			factor: 4.4482216152605,
		}),
		standard({
			id: "[Btu]",
			dimension: "energy",
			canonicalUnit: "J",
			baseDimensionVector: ENERGY_VECTOR,
			composable: true,
			bundle: "us-customary",
			factor: 1_055.05585262,
		}),
		standard({
			id: "[hp]",
			dimension: "power",
			canonicalUnit: "W",
			baseDimensionVector: POWER_VECTOR,
			composable: true,
			bundle: "us-customary",
			factor: 745.699871582,
		}),
	];
}
