export const EditorAction = {
	ExitInsertMode: "EXIT_INSERT",
	SubmitMacro: "SUBMIT_MACRO",
	UnlockMacro: "UNLOCK_MACRO",
	LockMacro: "LOCK_MACRO",
	MoveCursor: "MOVE_CURSOR",
	CursorHome: "CURSOR_HOME",
	CursorEnd: "CURSOR_END",
	TypeChar: "TYPE_CHAR",
	Backspace: "BACKSPACE",
	Redo: "REDO",
	ExitVisualMode: "EXIT_VISUAL",
	DeleteSelection: "DELETE_SELECTION",
	YankSelection: "YANK_SELECTION",
	RunCell: "RUN_CELL",
	ExtendSelectionDown: "EXTEND_SELECTION_DOWN",
	ExtendSelectionUp: "EXTEND_SELECTION_UP",
	SwapSelectionAnchor: "SWAP_SELECTION_ANCHOR",
	OpenCommandLine: "OPEN_COMMAND_LINE",
	Quit: "QUIT",
	DeleteCell: "DELETE_CELL",
	YankCell: "YANK_CELL",
	PrevError: "PREV_ERROR",
	NextError: "NEXT_ERROR",
	OpenWorkspace: "OPEN_WORKSPACE",
	MoveDown: "MOVE_DOWN",
	MoveUp: "MOVE_UP",
	EnterInsertMode: "ENTER_INSERT",
	InsertBelow: "INSERT_BELOW",
	InsertAbove: "INSERT_ABOVE",
	Info: "INFO",
	PasteCell: "PASTE_CELL",
	PasteCellAbove: "PASTE_CELL_ABOVE",
	PreviewCell: "PREVIEW_CELL",
	Undo: "UNDO",
	OpenMacroInput: "ENTER_MACRO",
	Search: "SEARCH",
	EnterVisualMode: "ENTER_VISUAL",
} as const;

export type EditorAction = (typeof EditorAction)[keyof typeof EditorAction];
