import { OPERATIONAL_DOMAINS } from "../schemas-interface/environment";
import {
	EQUIPMENT_STATUSES,
	OPERATIONAL_GEAR_CATEGORIES,
	PROTECTIVE_ITEM_STATUSES,
} from "../schemas-interface/injury";
import { CLINICAL_SOURCE_TYPES } from "../schemas-interface/shared";
import { defineSchema } from "../schema-factory";
import { productDetailsFields } from "./shared-fields";

export const mechanicalInjurySchema = defineSchema({
	schema: "MechanicalInjury",
	version: 1,
	status: "published",
	fields: {
		id: {
			path: "id",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: true,
		},
		soapSection: {
			path: "soapSection",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: ["subjective", "objective"],
		},
		energyTransferMechanism: {
			path: "energyTransferMechanism",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: [
				"blunt_impact",
				"penetrating_projectile",
				"penetrating_sharp",
				"blast_overpressure",
				"crush_compression",
				"avulsion_shearing",
				"barotrauma",
				"thermal_burn",
			],
		},
		anatomyLocations: {
			path: "anatomyLocations",
			valueKind: "concept_array",
			cardinality: "many",
			required: false,
			conceptResolution: { required: true },
		},
		ballisticProfile: {
			path: "ballisticProfile",
			valueKind: "composite",
			cardinality: "one",
			required: false,
		},
		"ballisticProfile.firearmOrOrdnance": {
			path: "ballisticProfile.firearmOrOrdnance",
			valueKind: "concept",
			cardinality: "one",
			required: false,
			conceptResolution: { required: true },
		},
		"ballisticProfile.caliber": {
			path: "ballisticProfile.caliber",
			valueKind: "concept",
			cardinality: "one",
			required: false,
			conceptResolution: { required: true },
		},
		"ballisticProfile.projectileType": {
			path: "ballisticProfile.projectileType",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: false,
		},
		"ballisticProfile.estimatedStandoffDistance": {
			path: "ballisticProfile.estimatedStandoffDistance",
			valueKind: "measurement",
			cardinality: "one",
			required: false,
			measurement: { dimension: "length" },
		},
		"ballisticProfile.armorPenetrationStatus": {
			path: "ballisticProfile.armorPenetrationStatus",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: ["defeated_by_armor", "penetrated_armor", "unprotected"],
		},
		blastProfile: {
			path: "blastProfile",
			valueKind: "composite",
			cardinality: "one",
			required: false,
		},
		"blastProfile.blastWaveType": {
			path: "blastProfile.blastWaveType",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: [
				"primary_overpressure",
				"secondary_shrapnel",
				"tertiary_impact",
				"quaternary_burn_chemical",
			],
		},
		"blastProfile.detonationStandoffDistance": {
			path: "blastProfile.detonationStandoffDistance",
			valueKind: "measurement",
			cardinality: "one",
			required: false,
			measurement: { dimension: "length" },
		},
		"blastProfile.enclosedSpace": {
			path: "blastProfile.enclosedSpace",
			valueKind: "scalar",
			scalarType: "boolean",
			cardinality: "one",
			required: false,
		},
		fallProfile: {
			path: "fallProfile",
			valueKind: "composite",
			cardinality: "one",
			required: false,
		},
		"fallProfile.fallHeight": {
			path: "fallProfile.fallHeight",
			valueKind: "measurement",
			cardinality: "one",
			required: true,
			measurement: { dimension: "length" },
		},
		"fallProfile.impactSurface": {
			path: "fallProfile.impactSurface",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: false,
		},
		"fallProfile.freefall": {
			path: "fallProfile.freefall",
			valueKind: "scalar",
			scalarType: "boolean",
			cardinality: "one",
			required: false,
		},
	},
});

export const protectiveEquipmentSchema = defineSchema({
	schema: "ProtectiveEquipment",
	version: 1,
	status: "published",
	fields: {
		id: {
			path: "id",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: true,
		},
		soapSection: {
			path: "soapSection",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: ["subjective", "objective"],
		},
		equipmentStatus: {
			path: "equipmentStatus",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: EQUIPMENT_STATUSES,
		},
		verifiedDeployedGear: {
			path: "verifiedDeployedGear",
			valueKind: "composite",
			cardinality: "many",
			required: true,
		},
		"verifiedDeployedGear[].status": {
			path: "verifiedDeployedGear[].status",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: PROTECTIVE_ITEM_STATUSES,
		},
		"verifiedDeployedGear[].gearCategory": {
			path: "verifiedDeployedGear[].gearCategory",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: OPERATIONAL_GEAR_CATEGORIES,
		},
		"verifiedDeployedGear[].id": {
			path: "verifiedDeployedGear[].id",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: true,
		},
		"verifiedDeployedGear[].operationalDomain": {
			path: "verifiedDeployedGear[].operationalDomain",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: OPERATIONAL_DOMAINS,
		},
		sourceType: {
			path: "sourceType",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: CLINICAL_SOURCE_TYPES,
		},
		dateRange: {
			path: "dateRange",
			valueKind: "temporal",
			temporalType: "date_range",
			cardinality: "one",
			required: false,
		},
		...productDetailsFields({
			base: "verifiedDeployedGear[]",
			name: "details",
		}),
	},
});
