import { defineSchema } from "../schema-factory";
import {
	ADMINISTRATIVE_GENDERS,
	CULTIVATION_ENVIRONMENTS,
	GENETIC_MODIFICATION_STATUSES,
	PROPAGATION_METHODS,
	SUBJECT_LIFECYCLE_STATUSES,
} from "../schemas-interface/patient";

export const patientSchema = defineSchema({
	schema: "Patient",
	version: 1,
	status: "published",
	fields: {
		id: {
			path: "id",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: true,
		},
		mrn: {
			path: "mrn",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: true,
		},
		name: {
			path: "name",
			valueKind: "composite",
			cardinality: "one",
			required: true,
		},
		"name.primaryOrSurname": {
			path: "name.primaryOrSurname",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: true,
		},
		"name.prefixOrTitle": {
			path: "name.prefixOrTitle",
			valueKind: "scalar",
			scalarType: "string",
			cardinality: "one",
			required: false,
		},
		"name.givenNames": {
			path: "name.givenNames",
			valueKind: "composite",
			cardinality: "many",
			required: false,
		},
		administrativeGender: {
			path: "administrativeGender",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: ADMINISTRATIVE_GENDERS,
		},
		lifecycle: {
			path: "lifecycle",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: SUBJECT_LIFECYCLE_STATUSES,
		},
		originationDate: {
			path: "originationDate",
			valueKind: "temporal",
			temporalType: "date",
			cardinality: "one",
			required: true,
		},
		isOriginationEstimated: {
			path: "isOriginationEstimated",
			valueKind: "scalar",
			scalarType: "boolean",
			cardinality: "one",
			required: true,
		},
		biologicalProfile: {
			path: "biologicalProfile",
			valueKind: "composite",
			cardinality: "one",
			required: true,
		},
		"biologicalProfile.organismType": {
			path: "biologicalProfile.organismType",
			valueKind: "enum",
			cardinality: "one",
			required: true,
			enumValues: ["human", "animal", "plant"],
		},
		"biologicalProfile.race": {
			path: "biologicalProfile.race",
			valueKind: "concept",
			cardinality: "one",
			required: false,
			conceptResolution: { required: true },
		},
		"biologicalProfile.ethnicity": {
			path: "biologicalProfile.ethnicity",
			valueKind: "concept",
			cardinality: "one",
			required: false,
			conceptResolution: { required: true },
		},
		"biologicalProfile.species": {
			path: "biologicalProfile.species",
			valueKind: "concept",
			cardinality: "one",
			required: false,
			conceptResolution: { required: true },
		},
		"biologicalProfile.breedOrCultivar": {
			path: "biologicalProfile.breedOrCultivar",
			valueKind: "concept",
			cardinality: "one",
			required: false,
			conceptResolution: { required: true },
		},
		"biologicalProfile.propagationMethod": {
			path: "biologicalProfile.propagationMethod",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: PROPAGATION_METHODS,
		},
		"biologicalProfile.geneticModificationStatus": {
			path: "biologicalProfile.geneticModificationStatus",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: GENETIC_MODIFICATION_STATUSES,
		},
		"biologicalProfile.cultivationEnvironment": {
			path: "biologicalProfile.cultivationEnvironment",
			valueKind: "enum",
			cardinality: "one",
			required: false,
			enumValues: CULTIVATION_ENVIRONMENTS,
		},
	},
});
