#!/usr/bin/env -S bun
/**
 * i18n tooling for @stateful-mcp/macro.
 *
 * Subcommands:
 *   keys   Regenerate src/workspace/i18n/locales/i18n-keys.ts from the en/
 *          locale modules. The generated file is the canonical key union
 *          (I18nKey) used to type t()/translate() call sites.
 *   check  Audit i18n coverage and exit non-zero on problems:
 *            - macro-web usages that have no translation in EN_LOCALE and are
 *              not provided by macro-web's gallery-locale.ts (missing strings)
 *            - EN_LOCALE keys missing from ES_LOCALE (incomplete translations)
 *            - keys defined in en/ modules but absent from the EN_LOCALE
 *              aggregator (aggregator gaps)
 *
 * Usage:
 *   bun scripts/i18n-tools.ts keys
 *   bun scripts/i18n-tools.ts check
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = join(here, "..");
const MACRO = join(ROOT, "packages", "macro");
const WEB = join(ROOT, "packages", "macro-web");
const LOCALES = join(MACRO, "src", "workspace", "i18n", "locales");
const KEYS_FILE = join(LOCALES, "i18n-keys.ts");
const EN_DIR = join(LOCALES, "en");
const ES_DIR = join(LOCALES, "es");
const GALLERY_FILE = join(WEB, "src", "lib", "gallery-locale.ts");

// ---------------------------------------------------------------------------
// Parsing helpers
// ---------------------------------------------------------------------------

/** Collect `"key":` literals from a TS source string. */
function parseKeyLiterals(src: string): string[] {
	const re = /"((?:\\.|[^"\\])*)"\s*:/g;
	const out: string[] = [];
	let m: RegExpExecArray | null;
	m = re.exec(src);
	while (m) {
		if (m[1]) out.push(m[1]);
		m = re.exec(src);
	}
	return out;
}

// Union of every "key": literal in dir/**/*.ts (the per-domain modules).
function collectModuleKeys(dir: string): Set<string> {
	const keys = new Set<string>();
	if (!existsSync(dir)) return keys;
	for (const f of readdirSync(dir, { recursive: true })) {
		const rel = String(f);
		if (!rel.endsWith(".ts")) continue;
		const src = readFileSync(join(dir, rel), "utf8");
		for (const k of parseKeyLiterals(src)) keys.add(k);
	}
	return keys;
}

/** Keys nested under `topKey: { ... }` (used for GALLERY_TRANSLATIONS.en). */
function nestedKeys(src: string, topKey: string): Set<string> {
	const idx = src.indexOf(`${topKey}:`);
	if (idx < 0) return new Set();
	const brace = src.indexOf("{", idx);
	let i = brace + 1;
	let depth = 1;
	let buf = "";
	while (i < src.length && depth > 0) {
		const c = src[i];
		if (c === "{") depth++;
		else if (c === "}") {
			depth--;
			if (depth === 0) break;
		}
		buf += c;
		i++;
	}
	return new Set(parseKeyLiterals(buf));
}

/** Runtime key set from a locale aggregator (e.g. en.ts -> EN_LOCALE). */
async function runtimeKeys(file: string): Promise<Set<string>> {
	const mod = await import(file);
	const dict = (mod.EN_LOCALE ?? mod.ES_LOCALE) as Record<string, string>;
	return new Set(Object.keys(dict));
}

// ---------------------------------------------------------------------------
// `keys` subcommand
// ---------------------------------------------------------------------------

function renderKeys(keys: Iterable<string>): string {
	const sorted = [...keys].sort();
	const body = sorted.map((k) => `\t${JSON.stringify(k)},`).join("\n");
	return (
		"// GENERATED by scripts/i18n-tools.ts (subcommand: keys). Do not edit by hand.\n" +
		"export const I18N_KEYS = [\n" +
		body +
		"\n] as const;\n\n" +
		"export type I18nKey = (typeof I18N_KEYS)[number];\n"
	);
}

function cmdKeys(): void {
	const keys = collectModuleKeys(EN_DIR);
	const next = renderKeys(keys);
	const prev = existsSync(KEYS_FILE) ? readFileSync(KEYS_FILE, "utf8") : "";
	if (prev === next) {
		console.log(`i18n-keys.ts: up to date (${keys.size} keys).`);
		return;
	}
	writeFileSync(KEYS_FILE, next, "utf8");
	console.log(`i18n-keys.ts: wrote ${keys.size} keys.`);
}

// ---------------------------------------------------------------------------
// `check` subcommand
// ---------------------------------------------------------------------------

const CALL_RES = [
	/\bt\(\s*['"]([\w.]+)['"]/g,
	/translate\(\s*[^,]+,\s*['"]([\w.]+)['"]/g,
	/resolveLabel\(\s*[^,]+,\s*['"]([\w.]+)['"]/g,
	/kernel\.t\(\s*['"]([\w.]+)['"]/g,
	/i18n\.t\(\s*['"]([\w.]+)['"]/g,
];

function extractUsedKeys(rootDir: string, skip: Set<string>): Set<string> {
	const used = new Set<string>();
	const walk = (d: string): void => {
		for (const e of readdirSync(d, { withFileTypes: true })) {
			const p = join(d, e.name);
			if (e.isDirectory()) {
				if (e.name === "node_modules" || e.name === "dist") continue;
				walk(p);
				continue;
			}
			if (!/\.(tsx?|jsx?|svelte|vue)$/.test(e.name)) continue;
			if (/\.test\.(tsx?|jsx?)$/.test(e.name)) continue;
			if (skip.has(p)) continue;
			const s = readFileSync(p, "utf8");
			for (const re of CALL_RES) {
				let m: RegExpExecArray | null;
				m = re.exec(s);
				while (m) {
					if (m[1]) used.add(m[1]);
					m = re.exec(s);
				}
			}
		}
	};
	walk(rootDir);
	return used;
}

async function cmdCheck(): Promise<void> {
	const problems: string[] = [];

	const enModuleKeys = collectModuleKeys(EN_DIR);
	const enLocale = await runtimeKeys(join(LOCALES, "en.ts"));
	const esModuleKeys = collectModuleKeys(ES_DIR);

	const gallerySrc = readFileSync(GALLERY_FILE, "utf8");
	const galleryEn = nestedKeys(gallerySrc, "en");

	// 1. macro-web usages with no translation anywhere.
	const webUsed = extractUsedKeys(join(WEB, "src"), new Set([GALLERY_FILE]));
	const missingTranslations = [...webUsed]
		.filter((k) => !enLocale.has(k) && !galleryEn.has(k))
		.sort();
	if (missingTranslations.length > 0) {
		problems.push(
			`${missingTranslations.length} macro-web key(s) used but never translated:\n` +
				missingTranslations.map((k) => `    - ${k}`).join("\n"),
		);
	}

	// 2. EN -> ES parity.
	const esMissing = [...enModuleKeys]
		.filter((k) => !esModuleKeys.has(k))
		.sort();
	if (esMissing.length > 0) {
		problems.push(
			`${esMissing.length} EN key(s) missing from ES_LOCALE:\n` +
				esMissing.map((k) => `    - ${k}`).join("\n"),
		);
	}

	// 3. Aggregator gaps: module keys not present in the merged EN_LOCALE.
	const aggGaps = [...enModuleKeys].filter((k) => !enLocale.has(k)).sort();
	if (aggGaps.length > 0) {
		problems.push(
			`${aggGaps.length} key(s) defined in en/ modules but absent from EN_LOCALE aggregator:\n` +
				aggGaps.map((k) => `    - ${k}`).join("\n"),
		);
	}

	if (problems.length > 0) {
		console.error("i18n check FAILED:\n");
		console.error(problems.join("\n\n"));
		process.exit(1);
	}
	console.log(
		`i18n check OK (${enModuleKeys.size} keys; ` +
			`${webUsed.size} macro-web usages; ` +
			`EN/ES parity ${esMissing.length ? "BROKEN" : "clean"}).`,
	);
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
	const sub = process.argv[2];
	switch (sub) {
		case "keys":
			cmdKeys();
			return;
		case "check":
			await cmdCheck();
			return;
		case undefined:
		case "help":
		case "--help":
		case "-h":
			console.log(
				"usage: bun scripts/i18n-tools.ts <keys|check>\n" +
					"  keys   regenerate locales/i18n-keys.ts from the en/ modules\n" +
					"  check  audit i18n coverage (missing translations, ES parity, aggregator gaps)",
			);
			return;
		default:
			console.error(`unknown subcommand: ${sub}`);
			process.exit(2);
	}
}

main();
